# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=6, verbose_name='patente')),
                ('brand', models.CharField(max_length=32, verbose_name='marca')),
                ('model', models.CharField(max_length=32, verbose_name='modelo')),
                ('year', models.IntegerField(blank=True, verbose_name='año')),
                ('capacity', models.IntegerField(verbose_name='capacidad')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('notes', models.CharField(blank=True, max_length=128, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'bus',
                'ordering': ['company', 'plate'],
                'verbose_name_plural': 'buses',
            },
        ),
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'empresa de buses',
                'ordering': ['name'],
                'verbose_name_plural': 'empresas de buses',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=8, verbose_name='nombre corto')),
                ('id_string', models.CharField(blank=True, max_length=16, verbose_name='RUT')),
                ('line_of_business', models.CharField(max_length=64, verbose_name='giro')),
                ('address', models.CharField(max_length=64, verbose_name='dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'empresa',
                'ordering': ['name'],
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=16, verbose_name='nombre corto')),
            ],
            options={
                'verbose_name': 'destino',
                'ordering': ['name'],
                'verbose_name_plural': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(max_length=16, verbose_name='RUT')),
                ('names', models.CharField(max_length=32, verbose_name='nombres')),
                ('surnames', models.CharField(max_length=32, verbose_name='apellidos')),
            ],
            options={
                'verbose_name': 'chofer',
                'ordering': ['surnames', 'names'],
                'verbose_name_plural': 'choferes',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(max_length=16, verbose_name='ID')),
                ('external_id', models.CharField(max_length=16, verbose_name='ID Externo')),
                ('debt', models.PositiveIntegerField(verbose_name='deuda')),
                ('charge', models.PositiveIntegerField(verbose_name='costo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'grupo',
                'ordering': ['external_id'],
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'tipo de identificación',
                'ordering': ['name'],
                'verbose_name_plural': 'tipos de identificación',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_people', models.IntegerField(verbose_name='PAX')),
                ('guides', models.IntegerField(verbose_name='guías')),
            ],
            options={
                'verbose_name': 'itinerario',
                'ordering': ['stretch', 'app_people', 'guides'],
                'verbose_name_plural': 'itinerarios',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_string', models.CharField(max_length=16, verbose_name='identificación')),
                ('names', models.CharField(max_length=32, verbose_name='nombres')),
                ('surnames', models.CharField(max_length=32, verbose_name='apellidos')),
                ('date_of_birth', models.DateField(verbose_name='fecha de nacimiento')),
                ('sex', models.CharField(choices=[('m', 'masculino'), ('f', 'femenino')], max_length=1, verbose_name='sexo')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.IDType', verbose_name='tipo de identificación')),
            ],
            options={
                'verbose_name': 'pasajero',
                'ordering': ['id_type', 'id_string'],
                'verbose_name_plural': 'pasajeros',
            },
        ),
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tramo',
                'ordering': ['description'],
                'verbose_name_plural': 'tramos',
            },
        ),
        migrations.CreateModel(
            name='StretchDestinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='posición')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Destination', verbose_name='destino')),
                ('stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Stretch')),
            ],
            options={
                'verbose_name': 'destino',
                'ordering': ['position'],
                'verbose_name_plural': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='hora')),
                ('notes', models.CharField(blank=True, max_length=128, verbose_name='notas')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Bus', verbose_name='bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.Driver', verbose_name='chofer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Group', verbose_name='grupo')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Itinerary', verbose_name='itinerario')),
            ],
            options={
                'verbose_name': 'viaje',
                'ordering': ['date', 'time'],
                'verbose_name_plural': 'viajes',
            },
        ),
        migrations.AddField(
            model_name='stretch',
            name='destinations',
            field=models.ManyToManyField(through='transport.StretchDestinations', to='transport.Destination'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='stretch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Stretch', verbose_name='tramo'),
        ),
        migrations.AddField(
            model_name='group',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='transport.Passenger', verbose_name='pasajeros'),
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.BusCompany', verbose_name='empresa'),
        ),
    ]
